FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9 --activate

COPY server/package.json server/pnpm-lock.yaml ./
RUN pnpm install

COPY server .
COPY shared /shared

CMD ["pnpm", "dev"]