// AUTO-GENERATED by shared/scripts/gen-page-types.mjs — DO NOT EDIT.
// Run `node shared/scripts/gen-page-types.mjs` after adding/renaming a *.types.shared.ts file
// (or run it with --watch). Each module is re-exported as a namespace.

export * as Footer from './footer.pageData.types.shared'
export * as Header from './header.pageData.types.shared'
export * as Home from './home.pageData.types.shared'
export * as Login from './login.pageData.types.shared'
export * as Profile from './profile.pageData.types.shared'
export * as Register from './register.pageData.types.shared'
export * as ReportCreate from './reportCreate.types.shared'
